[workspace]
resolver = "2"
members = ["crates/common", "programs/coupon_vault", "programs/coupon_market", "programs/coupon_faucet"]

[workspace.dependencies]
solana-program = "2.2"
coupon_common = { path = "crates/common" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
